name: Crypto Signal Bot
on: 
  workflow_dispatch:
  schedule:
    - cron: '*/3 * * * *'
permissions:
  contents: write
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python start.py
        env:
          TELEGRAM_BOT_TOKEN: \${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: \${{ secrets.TELEGRAM_CHAT_ID }}
          WEBHOOK_SECRET: \${{ secrets.WEBHOOK_SECRET }}
      - name: Commit cache
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "bot@github.com"
          git add .cache/
          git diff --quiet && git diff --staged --quiet || \
            (git commit -m "Update cache [skip ci]" && git push)
