name: Crypto Signal Bot

on:
  schedule:
    - cron: '*/3 * * * *'
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to commit cache files
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for git history

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: \${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: \${{ secrets.TELEGRAM_CHAT_ID }}
          WEBHOOK_SECRET: \${{ secrets.WEBHOOK_SECRET }}
        run: |
          python start.py

      - name: Commit state
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "bot@github.com"
          git add .cache/
          git diff --quiet && git diff --staged --quiet || \
            (git commit -m "Update cache [skip ci]" && git push)
